name: Flyway Migration

on:
  workflow_dispatch:
  push:
    paths:
      - 'sql/**'
      - 'flyway.conf'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flyway CLI
        run: |
          wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.13.0/flyway-commandline-10.13.0-linux-x64.tar.gz
          tar -xzf flyway-commandline-10.13.0-linux-x64.tar.gz
          sudo mv flyway-10.13.0 /opt/flyway
          echo "/opt/flyway" >> $GITHUB_PATH

      - name: Run Flyway migration
        env:
          FLYWAY_URL: ${{ secrets.FLYWAY_URL }}
          FLYWAY_USER: ${{ secrets.FLYWAY_USER }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
        run: |
          /opt/flyway/flyway migrate -configFiles=flyway.conf -locations=filesystem:/sql
